import { SchoolLevel } from '../../../domain/entities/school-level.js';
import type {
  CalculatorField,
  CalculatorSchema,
} from '../../../domain/entities/calculator-schema.js';

export type MissionSubject =
  | 'Mathématiques'
  | 'Physique'
  | 'Chimie'
  | 'SVT';

export interface HistoryOfScienceMission {
  /** Code de l'issue d'origine, ex. "1.1". */
  code: string;
  subject: MissionSubject;
  level: SchoolLevel;
  title: string;
  durationMinutes: number;
  narrativeIntro: string;
  theoryExplanation: string;
  calculatorSchema: CalculatorSchema;
}

/**
 * Métadonnées de chaque grandeur mesurable, partagées par toutes les missions.
 * La clé correspond à celle attendue par le calculateur côté application mobile
 * (`mobile/src/application/calculators/*`).
 */
const FIELD_META: Record<string, Omit<CalculatorField, 'key'>> = {
  // Mathématiques
  perimeterM: { label: 'Périmètre mesuré', unit: 'm', min: 0.05, max: 60 },
  diameterM: { label: 'Diamètre', unit: 'm', min: 0.01, max: 20 },
  lengthM: { label: 'Longueur', unit: 'm', min: 0.1, max: 50 },
  widthM: { label: 'Largeur', unit: 'm', min: 0.1, max: 50 },
  referenceInput: { label: 'Référence : entrée', unit: '', min: 0.01, max: 100000 },
  referenceOutput: { label: 'Référence : sortie', unit: '', min: 0, max: 100000 },
  targetInput: { label: 'Valeur cible : entrée', unit: '', min: 0.01, max: 100000 },
  dividend: { label: 'Dividende', unit: '', min: 0, max: 1000000000000 },
  divisor: { label: 'Diviseur', unit: '', min: 1, max: 1000000000 },
  pointDistanceToAxisM: { label: "Distance du point à l'axe", unit: 'm', min: 0, max: 20 },
  imageDistanceToAxisM: { label: "Distance de l'image à l'axe", unit: 'm', min: 0, max: 20 },
  radiusM: { label: 'Rayon', unit: 'm', min: 0.01, max: 30 },
  credits: { label: 'Total des crédits (fortunes)', unit: '', min: 0, max: 1000000000 },
  debits: { label: 'Total des débits (dettes)', unit: '', min: 0, max: 1000000000 },
  a: { label: 'Premier nombre', unit: '', min: 1, max: 100000 },
  b: { label: 'Second nombre', unit: '', min: 1, max: 100000 },
  shadowAngleDeg: { label: "Écart d'angle d'ombre entre les deux villes", unit: '°', min: 0.1, max: 90 },
  distanceKm: { label: 'Distance entre les deux villes', unit: 'km', min: 1, max: 20000 },
  x1: { label: 'Abscisse du point A', unit: '', min: -1000, max: 1000 },
  y1: { label: 'Ordonnée du point A', unit: '', min: -1000, max: 1000 },
  x2: { label: 'Abscisse du point B', unit: '', min: -1000, max: 1000 },
  y2: { label: 'Ordonnée du point B', unit: '', min: -1000, max: 1000 },
  legAM: { label: "Premier côté de l'angle droit", unit: 'm', min: 0.01, max: 50 },
  legBM: { label: "Second côté de l'angle droit", unit: 'm', min: 0.01, max: 50 },
  stickHeightM: { label: 'Hauteur du bâton', unit: 'm', min: 0.1, max: 3 },
  stickShadowM: { label: "Longueur de l'ombre du bâton", unit: 'm', min: 0.05, max: 10 },
  targetShadowM: { label: "Longueur de l'ombre de l'objet", unit: 'm', min: 0.05, max: 60 },
  containerVolumeCm3: { label: 'Volume du récipient', unit: 'cm³', min: 1, max: 10000000 },
  grainsPerCm3: { label: 'Nombre de grains par cm³', unit: '', min: 1, max: 10000000 },
  sideM: { label: 'Côté du carré', unit: 'm', min: 0.01, max: 30 },
  distanceM: { label: 'Distance', unit: 'm', min: 0.1, max: 5000 },
  elevationAngleDeg: { label: "Angle d'élévation visé", unit: '°', min: 0.1, max: 89.9 },
  eyeHeightM: { label: 'Hauteur des yeux au-dessus du sol', unit: 'm', min: 0, max: 2.5 },
  timeS: { label: 'Durée', unit: 's', min: 0.01, max: 3600 },
  baseM: { label: 'Longueur de la base mesurée', unit: 'm', min: 0.5, max: 500 },
  angleADeg: { label: 'Angle visé depuis A', unit: '°', min: 0.1, max: 179 },
  angleBDeg: { label: 'Angle visé depuis B', unit: '°', min: 0.1, max: 179 },
  favorableOutcomes: { label: 'Nombre de cas favorables', unit: '', min: 0, max: 100000 },
  totalOutcomes: { label: 'Nombre de cas possibles', unit: '', min: 1, max: 100000 },

  // Physique
  objectVelocityMs: { label: "Vitesse de l'objet", unit: 'm/s', min: -200, max: 200 },
  observerVelocityMs: { label: "Vitesse de l'observateur", unit: 'm/s', min: -200, max: 200 },
  massKg: { label: 'Masse', unit: 'kg', min: 0.01, max: 1000 },
  gravityNPerKg: { label: 'Intensité de la pesanteur du lieu', unit: 'N/kg', min: 0.1, max: 30 },
  massG: { label: 'Masse', unit: 'g', min: 0.1, max: 100000 },
  displacedVolumeCm3: { label: "Volume d'eau déplacé", unit: 'cm³', min: 0.1, max: 100000 },
  realValueKm: { label: 'Grandeur réelle', unit: 'km', min: 0.1, max: 10000000000 },
  kmPerCm: { label: 'Km représentés par 1 cm de maquette', unit: 'km/cm', min: 0.001, max: 1000000000 },
  gnomonHeightM: { label: 'Hauteur du gnomon', unit: 'm', min: 0.05, max: 3 },
  shadowLengthM: { label: "Longueur de l'ombre", unit: 'm', min: 0.01, max: 50 },
  objectSizeM: { label: "Taille de l'objet", unit: 'm', min: 0.01, max: 100 },
  objectDistanceM: { label: "Distance de l'objet", unit: 'm', min: 0.1, max: 5000 },
  boxDepthM: { label: 'Profondeur de la chambre noire', unit: 'm', min: 0.02, max: 2 },
  phaseAngleDeg: { label: 'Angle de phase Soleil-Lune', unit: '°', min: 0, max: 360 },
  cellCount: { label: "Nombre d'éléments empilés", unit: '', min: 1, max: 100 },
  voltagePerCellV: { label: 'Tension par élément', unit: 'V', min: 0.01, max: 5 },
  branchCurrent1A: { label: 'Intensité de la branche 1', unit: 'A', min: 0, max: 20 },
  branchCurrent2A: { label: 'Intensité de la branche 2', unit: 'A', min: 0, max: 20 },
  voltageV: { label: 'Tension mesurée', unit: 'V', min: 0, max: 400 },
  currentA: { label: 'Intensité mesurée', unit: 'A', min: 0.0001, max: 50 },
  lineSpacingNm: { label: 'Pas du réseau', unit: 'nm', min: 100, max: 10000 },
  diffractionAngleDeg: { label: 'Angle de diffraction de la couleur', unit: '°', min: 0.1, max: 89.9 },
  order: { label: 'Ordre de diffraction', unit: '', min: 1, max: 5 },
  objectiveFocalMm: { label: "Distance focale de l'objectif", unit: 'mm', min: 1, max: 5000 },
  eyepieceFocalMm: { label: "Distance focale de l'oculaire", unit: 'mm', min: 1, max: 500 },
  speedMs: { label: 'Vitesse de propagation', unit: 'm/s', min: 1, max: 300000000 },
  forceXN: { label: 'Force horizontale', unit: 'N', min: -1000, max: 1000 },
  forceYN: { label: 'Force verticale', unit: 'N', min: -1000, max: 1000 },

  // Chimie
  mass1G: { label: "Masse d'eau n°1", unit: 'g', min: 1, max: 100000 },
  temp1C: { label: "Température de l'eau n°1", unit: '°C', min: -20, max: 120 },
  mass2G: { label: "Masse d'eau n°2", unit: 'g', min: 1, max: 100000 },
  temp2C: { label: "Température de l'eau n°2", unit: '°C', min: -20, max: 120 },
  residueMassMg: { label: 'Masse du résidu sec', unit: 'mg', min: 0, max: 100000 },
  sampleVolumeL: { label: "Volume d'eau évaporé", unit: 'L', min: 0.001, max: 100 },
  distillateVolumeMl: { label: 'Volume de distillat recueilli', unit: 'mL', min: 0, max: 100000 },
  initialVolumeMl: { label: 'Volume initial', unit: 'mL', min: 0.1, max: 100000 },
  soluteMassG: { label: 'Masse de soluté', unit: 'g', min: 0, max: 100000 },
  solventMassG: { label: 'Masse de solvant', unit: 'g', min: 0.1, max: 100000 },
  soluteMigrationMm: { label: 'Migration du constituant', unit: 'mm', min: 0, max: 1000 },
  solventFrontMm: { label: 'Distance parcourue par le solvant', unit: 'mm', min: 0.1, max: 1000 },
  reactantsMassG: { label: 'Masse totale des réactifs', unit: 'g', min: 0, max: 100000 },
  productsMassG: { label: 'Masse totale des produits', unit: 'g', min: 0, max: 100000 },
  waterRiseMl: { label: "Montée d'eau dans le bocal", unit: 'mL', min: 0, max: 100000 },
  initialAirMl: { label: "Volume d'air initial", unit: 'mL', min: 0.1, max: 100000 },
  volumeAMl: { label: 'Volume du liquide A', unit: 'mL', min: 0.1, max: 100000 },
  volumeBMl: { label: 'Volume du liquide B', unit: 'mL', min: 0.1, max: 100000 },
  mixedVolumeMl: { label: 'Volume du mélange', unit: 'mL', min: 0.1, max: 200000 },
  referenceVolumeMl: { label: 'Volume du bocal de référence', unit: 'mL', min: 1, max: 100000 },
  referenceTimeS: { label: 'Durée de combustion de référence', unit: 's', min: 0.1, max: 100000 },
  targetVolumeMl: { label: 'Volume du bocal étudié', unit: 'mL', min: 1, max: 100000 },
  reactant1MassG: { label: 'Masse du réactif 1', unit: 'g', min: 0, max: 100000 },
  reactant2MassG: { label: 'Masse du réactif 2', unit: 'g', min: 0, max: 100000 },
  hydrogenVolumeMl: { label: 'Volume de dihydrogène', unit: 'mL', min: 0.1, max: 100000 },
  oxygenVolumeMl: { label: 'Volume de dioxygène', unit: 'mL', min: 0.1, max: 100000 },
  initialMassG: { label: 'Masse initiale', unit: 'g', min: 0.1, max: 100000 },
  finalMassG: { label: 'Masse finale', unit: 'g', min: 0, max: 100000 },
  initialPh: { label: 'pH initial de la solution', unit: '', min: 0, max: 6.9 },
  dilutionFactor: { label: 'Facteur de dilution', unit: '', min: 1, max: 1000000 },
  solutionCurrentMa: { label: 'Intensité avec la solution testée', unit: 'mA', min: 0, max: 100000 },
  referenceCurrentMa: { label: "Intensité avec l'eau de référence", unit: 'mA', min: 0.001, max: 100000 },

  // SVT
  fieldOfViewUm: { label: 'Diamètre du champ observé', unit: 'µm', min: 1, max: 10000 },
  cellsAcrossField: { label: 'Nombre de cellules en travers du champ', unit: '', min: 1, max: 500 },
  sharedTraits: { label: 'Nombre d’attributs communs', unit: '', min: 0, max: 100 },
  observedTraits: { label: 'Nombre d’attributs observés', unit: '', min: 1, max: 100 },
  depthCm: { label: 'Profondeur de la strate', unit: 'cm', min: 0, max: 100000 },
  sedimentationRateCmPerCentury: { label: 'Vitesse de sédimentation', unit: 'cm/siècle', min: 0.01, max: 1000 },
  fossilMeasureMm: { label: 'Mesure sur le fossile', unit: 'mm', min: 0.1, max: 100000 },
  livingMeasureMm: { label: 'Mesure sur la forme actuelle', unit: 'mm', min: 0.1, max: 100000 },
  initialPlantMassG: { label: 'Masse initiale du plant', unit: 'g', min: 0.1, max: 100000 },
  finalPlantMassG: { label: 'Masse finale du plant', unit: 'g', min: 0.1, max: 10000000 },
  sinkingMm: { label: "Enfoncement de la dalle témoin", unit: 'mm', min: 0, max: 1000 },
  durationDays: { label: 'Durée du suivi', unit: 'jours', min: 1, max: 4000 },
  finalHeightMm: { label: 'Hauteur finale de la pâte', unit: 'mm', min: 1, max: 1000 },
  initialHeightMm: { label: 'Hauteur initiale de la pâte', unit: 'mm', min: 1, max: 1000 },
  sMinusPSeconds: { label: "Écart d'arrivée des ondes S et P", unit: 's', min: 0.1, max: 600 },
  flowDistanceM: { label: 'Distance parcourue par le front de coulée', unit: 'm', min: 0.01, max: 100000 },
  durationS: { label: 'Durée', unit: 's', min: 0.1, max: 100000 },
  breathVolumeMl: { label: "Volume d'un souffle", unit: 'mL', min: 50, max: 6000 },
  breathsPerMinute: { label: 'Nombre de respirations par minute', unit: '', min: 4, max: 80 },
  transformedFraction: { label: "Fraction d'amidon transformée", unit: '', min: 0, max: 1 },
  durationMin: { label: 'Durée', unit: 'min', min: 0.1, max: 240 },
  cases: { label: 'Nombre de malades parmi les exposés', unit: '', min: 0, max: 100000 },
  exposed: { label: 'Nombre total de personnes exposées', unit: '', min: 1, max: 100000 },
  bubbleCount: { label: 'Nombre de bulles comptées', unit: '', min: 0, max: 100000 },
  durationMinutes: { label: 'Durée du comptage', unit: 'min', min: 0.1, max: 240 },
  dominantCount: { label: 'Individus à caractère dominant', unit: '', min: 0, max: 100000 },
  recessiveCount: { label: 'Individus à caractère récessif', unit: '', min: 1, max: 100000 },
  strokeVolumeMl: { label: 'Volume de sang chassé par battement', unit: 'mL', min: 10, max: 250 },
  heartRateBpm: { label: 'Fréquence cardiaque', unit: 'bpm', min: 30, max: 220 },
  co2JarTempC: { label: 'Température du bocal enrichi en CO₂', unit: '°C', min: -20, max: 120 },
  airJarTempC: { label: "Température du bocal d'air ordinaire", unit: '°C', min: -20, max: 120 },
  rateCmPerYear: { label: 'Vitesse de déplacement de la plaque', unit: 'cm/an', min: 0, max: 30 },
  years: { label: 'Durée écoulée', unit: 'ans', min: 0, max: 1000000000 },
  controlAttackRate: { label: "Taux d'attaque du lot témoin", unit: '', min: 0.0001, max: 1 },
  vaccinatedAttackRate: { label: "Taux d'attaque du lot vacciné", unit: '', min: 0, max: 1 },
  waterMassG: { label: "Masse d'eau chauffée", unit: 'g', min: 1, max: 100000 },
  temperatureRiseC: { label: "Élévation de température de l'eau", unit: '°C', min: 0.1, max: 100 },
  waterVolumeMl: { label: "Volume d'eau versé", unit: 'mL', min: 1, max: 100000 },
  infiltrationTimeS: { label: "Temps d'infiltration complète", unit: 's', min: 0.1, max: 100000 },
  fruitCount: { label: 'Fleurs ayant donné un fruit', unit: '', min: 0, max: 100000 },
  flowerCount: { label: 'Nombre de fleurs suivies', unit: '', min: 1, max: 100000 },
};

function fieldOf(key: string): CalculatorField {
  const meta = FIELD_META[key];
  if (!meta) {
    throw new Error(`Grandeur inconnue dans le schéma de calcul : ${key}`);
  }
  return { key, ...meta };
}

const DURATION_BY_LEVEL: Record<string, number> = {
  [SchoolLevel.SIXIEME]: 30,
  [SchoolLevel.CINQUIEME]: 35,
  [SchoolLevel.QUATRIEME]: 40,
  [SchoolLevel.TROISIEME]: 45,
};

function m(
  code: string,
  subject: MissionSubject,
  level: SchoolLevel,
  title: string,
  narrativeIntro: string,
  theoryExplanation: string,
  formula: string,
  resultLabel: string,
  fieldKeys: string[],
): HistoryOfScienceMission {
  return {
    code,
    subject,
    level,
    title,
    durationMinutes: DURATION_BY_LEVEL[level] ?? 40,
    narrativeIntro,
    theoryExplanation,
    calculatorSchema: {
      formula,
      resultLabel,
      fields: fieldKeys.map(fieldOf),
    },
  };
}

const S6 = SchoolLevel.SIXIEME;
const S5 = SchoolLevel.CINQUIEME;
const S4 = SchoolLevel.QUATRIEME;
const S3 = SchoolLevel.TROISIEME;

export const HISTORY_OF_SCIENCE_MISSIONS: HistoryOfScienceMission[] = [
  // ------------------------- M1 · Mathématiques -------------------------
  m(
    '1.1', 'Mathématiques', S6,
    '[Maths·6e] π et le périmètre du cercle — Archimède (v. 250 av. J.-C.)',
    "À Syracuse, Archimède cherche un encadrement fiable de la longueur d'un cercle, dont les artisans ne connaissent que des valeurs grossières. Dans « La Mesure du cercle », il coince le cercle entre deux polygones jusqu'à 96 côtés et démontre 223/71 < π < 22/7.",
    "Le périmètre d'un disque est proportionnel à son diamètre : P = π × D. En roulant un objet circulaire sur un tour et en mesurant son diamètre, le quotient P / D retombe toujours autour de 3,14.",
    'pi-from-circle', 'Valeur de π estimée', ['perimeterM', 'diameterM'],
  ),
  m(
    '1.2', 'Mathématiques', S6,
    "[Maths·6e] L'angle droit et l'arpentage — les harpédonaptes d'Égypte (Hérodote)",
    "Après chaque crue du Nil, les « tendeurs de corde » égyptiens rétablissent les limites des champs. Sans instrument à angle droit, ils tendent une corde à 13 nœuds en triangle 3-4-5, qui forme forcément un angle droit.",
    "Un quadrilatère dont les deux diagonales sont égales à √(L² + l²) est un vrai rectangle : ses quatre angles sont droits.",
    'rectangle-diagonal', 'Longueur de diagonale attendue', ['lengthM', 'widthM'],
  ),
  m(
    '1.3', 'Mathématiques', S6,
    '[Maths·6e] La proportionnalité et la règle de trois — Fibonacci, Liber Abaci (1202)',
    "Les marchands italiens du XIIIe siècle jonglent avec des monnaies et des mesures différentes d'une ville à l'autre. Dans le « Liber Abaci », Fibonacci diffuse la règle de trois et les chiffres indo-arabes qui la rendent praticable.",
    "Dans une situation de proportionnalité, de trois grandeurs connues (a, b, c) on déduit la quatrième : x = b × c / a.",
    'fourth-proportional', 'Quatrième proportionnelle', ['referenceInput', 'referenceOutput', 'targetInput'],
  ),
  m(
    '1.4', 'Mathématiques', S6,
    '[Maths·6e] La division euclidienne et le calendrier — réforme grégorienne (1582)',
    "Le calendrier julien avance d'environ 3 jours tous les 400 ans. En 1582, la commission du pape Grégoire XIII supprime 10 jours et change la règle des années bissextiles à partir de divisions avec reste.",
    "La division euclidienne d'un entier par un autre donne un quotient et un reste : c'est ce reste (la fraction de jour) que le calendrier doit rattraper.",
    'euclidean-remainder', 'Reste de la division', ['dividend', 'divisor'],
  ),
  m(
    '1.5', 'Mathématiques', S6,
    "[Maths·6e] La symétrie axiale et les pavages — les zelliges de l'Alhambra (XIVe s.)",
    "Au palais nasride de l'Alhambra, à Grenade, les artisans couvrent les murs de mosaïques sans espace vide, en explorant systématiquement réflexions, rotations et translations.",
    "La symétrie axiale conserve les longueurs et les angles : un point et son image sont à la même distance de l'axe. L'écart entre ces deux distances mesure la qualité du tracé.",
    'axial-symmetry-error', 'Écart de symétrie', ['pointDistanceToAxisM', 'imageDistanceToAxisM'],
  ),
  m(
    '1.6', 'Mathématiques', S5,
    "[Maths·5e] L'aire du disque et la méthode d'exhaustion — Archimède ; Liu Hui (263)",
    "On ne sait longtemps mesurer que des polygones. Archimède, puis Liu Hui en Chine, encadrent le disque entre polygones inscrit et circonscrit en multipliant les côtés jusqu'à rendre l'écart négligeable.",
    "L'aire du disque vaut A = π × R². On l'encadre par des polygones dont on sait calculer l'aire, de plus en plus proches du cercle.",
    'disk-area', 'Aire du disque (m²)', ['radiusM'],
  ),
  m(
    '1.7', 'Mathématiques', S5,
    '[Maths·5e] Les nombres relatifs : fortunes et dettes — Brahmagupta (Inde, 628)',
    "Dans le « Brāhmasphuṭasiddhānta », Brahmagupta donne pour la première fois les règles de calcul avec le zéro et les quantités négatives, interprétées comme des « dettes » et des « fortunes ».",
    "Une fortune et une dette de même valeur s'annulent : le solde net d'un compte est la somme des crédits diminuée de la somme des débits, et peut être négatif.",
    'net-balance', 'Solde net', ['credits', 'debits'],
  ),
  m(
    '1.8', 'Mathématiques', S5,
    "[Maths·5e] Les nombres premiers et le crible d'Ératosthène (Alexandrie, v. 240 av. J.-C.)",
    "Ératosthène, à la tête de la Bibliothèque d'Alexandrie, met au point un procédé pour lister les nombres premiers sans tester chaque nombre : on garde 2 et on raye ses multiples, puis 3, puis 5…",
    "Deux engrenages de a et b dents reviennent en phase après un nombre de dents égal au plus petit commun multiple de a et b, que l'on obtient par décomposition en facteurs premiers.",
    'lowest-common-multiple', 'Plus petit commun multiple', ['a', 'b'],
  ),
  m(
    '1.9', 'Mathématiques', S5,
    "[Maths·5e] Mesurer la Terre avec une ombre — Ératosthène, Syène-Alexandrie (v. 240 av. J.-C.)",
    "Le jour du solstice, le Soleil éclaire le fond des puits à Syène tandis qu'un gnomon projette une ombre à Alexandrie. Ératosthène mesure l'angle (≈ 7,2°, soit 1/50 de tour) et en déduit la circonférence terrestre.",
    "Les rayons du Soleil arrivant parallèles, l'angle d'ombre entre deux villes d'un même méridien est la fraction de tour qui sépare leurs verticales : circonférence = distance × 360 / angle.",
    'earth-circumference', 'Circonférence terrestre (km)', ['shadowAngleDeg', 'distanceKm'],
  ),
  m(
    '1.10', 'Mathématiques', S5,
    "[Maths·5e] Se repérer dans le plan : les coordonnées — Descartes, La Géométrie (1637)",
    "En 1637, à Leyde, Descartes montre dans « La Géométrie » que tout point peut être décrit par un couple de nombres : la géométrie devient calcul, l'équation devient courbe.",
    "Dans un repère orthogonal, la distance entre deux points se calcule à partir de leurs coordonnées : d = √((x₂ − x₁)² + (y₂ − y₁)²).",
    'planar-distance', 'Distance entre les deux points', ['x1', 'y1', 'x2', 'y2'],
  ),
  m(
    '1.11', 'Mathématiques', S4,
    '[Maths·4e] Le théorème de Pythagore — tablette Plimpton 322 (Babylone) ; Crotone',
    "La tablette babylonienne Plimpton 322 (v. 1800 av. J.-C.) aligne déjà des triplets vérifiant a² + b² = c². C'est l'école de Pythagore, à Crotone, à qui l'on attribue la première démonstration générale.",
    "Dans un triangle rectangle, l'hypoténuse se calcule à partir des deux côtés de l'angle droit : c = √(a² + b²).",
    'pythagorean-hypotenuse', "Longueur de l'hypoténuse (m)", ['legAM', 'legBM'],
  ),
  m(
    '1.12', 'Mathématiques', S4,
    "[Maths·4e] Le théorème de Thalès et la hauteur de la pyramide — Thalès de Milet (VIe s. av. J.-C.)",
    "Plutarque et Diogène Laërce rapportent que Thalès, en Égypte, détermina la hauteur de la grande pyramide sans l'escalader, en comparant l'ombre d'un bâton à celle du monument au même instant.",
    "Deux objets éclairés par le même Soleil forment des triangles de même forme : le rapport hauteur / longueur d'ombre est identique. On en déduit une hauteur inaccessible depuis celle d'un bâton témoin.",
    'thales-shadow-ratio', "Hauteur estimée de l'objet", ['stickHeightM', 'stickShadowM', 'targetShadowM'],
  ),
  m(
    '1.13', 'Mathématiques', S4,
    "[Maths·4e] Les puissances de 10 : « L'Arénaire » d'Archimède",
    "Pour réfuter l'idée que le nombre de grains de sable est infini, Archimède construit dans « L'Arénaire » un système capable de nommer des nombres gigantesques et estime qu'il faudrait ~10⁶³ grains pour remplir l'Univers connu.",
    "Un tas « innombrable » se chiffre : nombre de grains = volume du récipient × nombre de grains par cm³, résultat qui s'exprime naturellement en puissances de 10.",
    'grain-count', 'Nombre estimé de grains', ['containerVolumeCm3', 'grainsPerCm3'],
  ),
  m(
    '1.14', 'Mathématiques', S4,
    "[Maths·4e] La racine carrée et l'incommensurable — Hippase de Métaponte (Ve s. av. J.-C.)",
    "Les pythagoriciens pensaient que toute longueur était un rapport d'entiers. La diagonale d'un carré de côté 1 les met en échec : son carré vaut 2 et aucune fraction n'a un carré égal à 2.",
    "La diagonale d'un carré de côté c vaut c × √2, un nombre que l'on ne peut qu'encadrer aussi finement qu'on veut.",
    'square-diagonal', 'Diagonale du carré (m)', ['sideM'],
  ),
  m(
    '1.15', 'Mathématiques', S4,
    '[Maths·4e] La trigonométrie du triangle rectangle — Hipparque de Nicée ; Ptolémée',
    "Pour calculer des positions sur la sphère céleste, Hipparque dresse vers 150 av. J.-C. la première table de cordes, reprise et affinée par Ptolémée dans l'« Almageste ».",
    "Un angle d'élévation et une distance au pied d'un objet suffisent pour sa hauteur : h = distance × tan(angle) + hauteur des yeux.",
    'height-from-angle', 'Hauteur estimée (m)', ['distanceM', 'elevationAngleDeg', 'eyeHeightM'],
  ),
  m(
    '1.16', 'Mathématiques', S3,
    '[Maths·3e] La fonction et le graphique — Nicole Oresme (Paris, XIVe s.)',
    "Dans son « Traité des configurations des qualités », Nicole Oresme porte l'étendue sur une ligne et l'intensité sur des segments verticaux : la figure « montre » comment une grandeur dépend d'une autre.",
    "Pour un mouvement à allure régulière, la distance est proportionnelle au temps : le graphique est une droite dont la pente est la vitesse moyenne, v = d / t.",
    'average-speed', 'Vitesse moyenne (m/s)', ['distanceM', 'timeS'],
  ),
  m(
    '1.17', 'Mathématiques', S3,
    '[Maths·3e] Le mètre et la méridienne — Delambre et Méchain (1792-1799)',
    "Pour définir une unité universelle, Delambre et Méchain mesurent de 1792 à 1799 l'arc de méridien Dunkerque-Barcelone par triangulation : une seule base au sol, tous les autres côtés calculés par les angles.",
    "Un triangle est entièrement déterminé par un côté et deux angles : AC = base × sin(B) / sin(A + B). On obtient de longues distances sans les parcourir.",
    'triangulation-distance', 'Distance calculée (m)', ['baseM', 'angleADeg', 'angleBDeg'],
  ),
  m(
    '1.18', 'Mathématiques', S3,
    '[Maths·3e] Le hasard mis en équation — Pascal et Fermat (1654)',
    "En 1654, le chevalier de Méré soumet à Pascal le problème du partage des mises d'une partie interrompue. La correspondance Pascal-Fermat fonde le calcul des probabilités.",
    "Dans une situation d'équiprobabilité, la probabilité d'un événement est le quotient du nombre de cas favorables par le nombre de cas possibles, entre 0 et 1.",
    'equiprobability', 'Probabilité', ['favorableOutcomes', 'totalOutcomes'],
  ),

  // ------------------------- M2 · Physique -------------------------
  m(
    '2.1', 'Physique', S6,
    '[Physique·6e] Le mouvement et sa relativité — Galilée, Dialogue (1632)',
    "Pour lever l'objection au mouvement de la Terre, Galilée imagine la cabine d'un navire : enfermé sans regarder dehors, aucun passager ne peut détecter un mouvement à vitesse constante.",
    "Le mouvement n'a de sens que par rapport à un observateur : la vitesse d'un objet vue par un observateur = vitesse de l'objet − vitesse de l'observateur.",
    'relative-velocity', 'Vitesse relative (m/s)', ['objectVelocityMs', 'observerVelocityMs'],
  ),
  m(
    '2.2', 'Physique', S6,
    '[Physique·6e] La vitesse et la chute des corps — Galilée, plan incliné (Padoue)',
    "Ne pouvant chronométrer une chute libre, Galilée fait rouler des billes sur un plan très peu incliné et découvre que la distance parcourue est proportionnelle au carré du temps, indépendamment de la masse.",
    "Un mouvement uniformément accéléré sans vitesse initiale suit d = ½ a t² : on en déduit l'accélération a = 2 d / t².",
    'acceleration-from-drop', 'Accélération (m/s²)', ['distanceM', 'timeS'],
  ),
  m(
    '2.3', 'Physique', S6,
    '[Physique·6e] Poids, masse et gravitation — Newton, Principia (1687)',
    "Newton unifie la chute d'une pomme et le mouvement de la Lune dans une même force, la gravitation universelle. Elle explique pourquoi un corps « pèse » moins en altitude ou sur la Lune.",
    "La masse (kg) est propre à la matière ; le poids (N) dépend de l'astre : P = m × g, où g est l'intensité de la pesanteur du lieu.",
    'weight-from-mass', 'Poids (N)', ['massKg', 'gravityNPerKg'],
  ),
  m(
    '2.4', 'Physique', S6,
    "[Physique·6e] La densité et la flottaison — Archimède et la couronne d'Hiéron II",
    "Chargé de vérifier sans l'abîmer si la couronne du roi Hiéron II est en or pur, Archimède compare le volume d'eau qu'elle déplace à celui d'une même masse d'or.",
    "La masse volumique = masse / volume déplacé. Comparée à celle de l'eau (1 g/cm³), elle dit si un corps flotte (< 1) ou coule (> 1).",
    'density', 'Masse volumique (g/cm³)', ['massG', 'displacedVolumeCm3'],
  ),
  m(
    '2.5', 'Physique', S6,
    '[Physique·6e] La place de la Terre dans le système solaire — Copernic (1543) ; Galilée (1610)',
    "Copernic place le Soleil au centre ; Galilée, à la lunette, découvre les satellites de Jupiter et les phases de Vénus. La matière est concentrée dans quelques astres séparés par un espace immense.",
    "Sur une maquette à l'échelle, la taille d'un astre = sa grandeur réelle divisée par le nombre de km représenté par 1 cm de maquette.",
    'scale-model', 'Taille sur la maquette (cm)', ['realValueKm', 'kmPerCm'],
  ),
  m(
    '2.6', 'Physique', S5,
    "[Physique·5e] Les ombres et la propagation rectiligne — le gnomon ionien ; Thalès",
    "En suivant l'ombre d'une tige verticale au fil du jour, les savants de Milet repèrent le midi, le nord et les solstices : c'est, selon le programme, « la première loi scientifique connue de l'Humanité ».",
    "La lumière se propageant en ligne droite, l'ombre a un bord net et une longueur calculable : hauteur du Soleil = arctan(hauteur du gnomon / longueur de l'ombre).",
    'sun-elevation-from-shadow', 'Hauteur du Soleil (°)', ['gnomonHeightM', 'shadowLengthM'],
  ),
  m(
    '2.7', 'Physique', S5,
    "[Physique·5e] Les sources de lumière et la vision — Ibn al-Haytham (Le Caire, v. 1021)",
    "Dans le « Kitāb al-Manāzir », Alhazen tranche entre les théories de la vision : on ne voit un objet éclairé que si de la lumière entre dans l'œil, comme dans une chambre noire.",
    "Dans une chambre noire, la taille de l'image = taille de l'objet × profondeur de la boîte / distance de l'objet (triangles semblables).",
    'pinhole-image-size', "Taille de l'image (m)", ['objectSizeM', 'objectDistanceM', 'boxDepthM'],
  ),
  m(
    '2.8', 'Physique', S5,
    "[Physique·5e] Les phases de la Lune et les éclipses — Aristarque de Samos",
    "Aristarque exploite la géométrie de la Lune à demi éclairée pour comparer les distances du Soleil et de la Lune ; Hérodote attribue à Thalès la prévision de l'éclipse de −585.",
    "La fraction éclairée de la Lune vue de la Terre dépend de l'angle de phase : f = (1 + cos(angle)) / 2, de 0 (nouvelle Lune) à 1 (pleine Lune).",
    'illuminated-fraction', 'Fraction éclairée', ['phaseAngleDeg'],
  ),
  m(
    '2.9', 'Physique', S5,
    '[Physique·5e] Le circuit électrique et la pile — Volta (Pavie, 1799-1800)',
    "Contre l'« électricité animale » de Galvani, Volta empile des disques de zinc et de cuivre séparés par du drap salé : la pile débite un courant continu stable, sans grenouille.",
    "Empiler des éléments identiques additionne les tensions : tension de la pile = nombre d'éléments × tension par élément.",
    'pile-voltage', 'Tension de la pile (V)', ['cellCount', 'voltagePerCellV'],
  ),
  m(
    '2.10', 'Physique', S4,
    '[Physique·4e] Intensité, tension et lois du courant — Ørsted (1820) ; Ampère (1820)',
    "Après qu'Ørsted a montré à Copenhague qu'un courant dévie une boussole, Ampère met en équations, en quelques semaines à Paris, les forces entre courants et fait de l'intensité une grandeur mesurable.",
    "Loi des nœuds : dans un circuit avec dérivations, l'intensité du tronc commun est la somme des intensités des branches.",
    'branch-current-sum', 'Intensité dans le tronc (A)', ['branchCurrent1A', 'branchCurrent2A'],
  ),
  m(
    '2.11', 'Physique', S4,
    "[Physique·4e] La loi d'Ohm — Georg Ohm (Cologne, 1827)",
    "Vers 1826, Ohm fait varier la tension appliquée à des fils métalliques et mesure l'intensité obtenue. Il publie en 1827 la relation U = R × I, longtemps mal accueillie.",
    "Pour un dipôle ohmique, la tension est proportionnelle à l'intensité ; le coefficient est la résistance : R = U / I (en ohms).",
    'ohm-resistance', 'Résistance (Ω)', ['voltageV', 'currentA'],
  ),
  m(
    '2.12', 'Physique', S4,
    '[Physique·4e] La décomposition de la lumière blanche — Newton, prisme (1666)',
    "Newton fait passer un filet de lumière solaire dans un prisme et obtient un spectre continu. Son « experimentum crucis » prouve que le prisme sépare sans teinter : la lumière blanche contient toutes les couleurs.",
    "Avec un réseau (ou un CD), l'écart angulaire d'une couleur donne sa longueur d'onde : λ = pas du réseau × sin(angle) / ordre de diffraction.",
    'grating-wavelength', "Longueur d'onde (nm)", ['lineSpacingNm', 'diffractionAngleDeg', 'order'],
  ),
  m(
    '2.13', 'Physique', S4,
    '[Physique·4e] Les lentilles et la lunette astronomique — Lippershey (1608) ; Galilée ; Kepler',
    "En 1608, à Middelbourg, Lippershey dépose une demande de brevet pour un instrument à deux lentilles. Dès 1609, Galilée construit la sienne et la tourne vers le ciel ; Kepler en explique le trajet des rayons.",
    "Le grossissement d'une lunette = distance focale de l'objectif / distance focale de l'oculaire.",
    'telescope-magnification', 'Grossissement', ['objectiveFocalMm', 'eyepieceFocalMm'],
  ),
  m(
    '2.14', 'Physique', S4,
    '[Physique·4e] La vitesse de la lumière — Rømer (1676) ; Fizeau (1849)',
    "À l'Observatoire de Paris, Rømer déduit du retard des éclipses de Io que la lumière a une vitesse finie. En 1849, Fizeau en donne la première mesure terrestre avec une roue dentée entre Suresnes et Montmartre.",
    "La lumière a une vitesse finie : durée de trajet = distance / vitesse. Sur les distances astronomiques, ces durées s'expriment en puissances de 10.",
    'light-travel-time', 'Durée de trajet (s)', ['distanceM', 'speedMs'],
  ),
  m(
    '2.15', 'Physique', S3,
    '[Physique·3e] Les forces et leur représentation — Stevin (1586) ; Newton (1687)',
    "Stevin établit la composition des forces par le parallélogramme grâce à sa « chaîne de billes » qui ne se met pas en mouvement toute seule. Newton en fixe le cadre général dans les « Principia ».",
    "Deux forces perpendiculaires se composent en une résultante de valeur √(Fx² + Fy²) (règle du parallélogramme).",
    'resultant-force', 'Force résultante (N)', ['forceXN', 'forceYN'],
  ),
  m(
    '2.16', 'Physique', S3,
    '[Physique·3e] L’énergie mécanique et sa conservation — Émilie du Châtelet (Cirey, 1740)',
    "Dans ses « Institutions de physique », Émilie du Châtelet défend la « force vive » (mv²) : l'enfoncement d'une bille dans l'argile croît comme le carré de la vitesse d'impact, non comme la vitesse.",
    "L'énergie de mouvement croît comme le carré de la vitesse : Ec = ½ m v² (en joules). Elle quadruple quand la vitesse double.",
    'kinetic-energy', 'Énergie cinétique (J)', ['massKg', 'speedMs'],
  ),

  // ------------------------- M3 · Chimie -------------------------
  m(
    '3.1', 'Chimie', S6,
    '[Chimie·6e] États de la matière et palier de température — Joseph Black (Glasgow, 1761)',
    "Black constate qu'un mélange de glace et d'eau reste bloqué à 0 °C tant qu'il fond, même chauffé : la chaleur apportée est « latente », elle sert à changer l'état.",
    "En mélangeant deux masses d'eau, la température d'équilibre est la moyenne pondérée par les masses : (m₁T₁ + m₂T₂) / (m₁ + m₂).",
    'mixture-temperature', "Température d'équilibre (°C)", ['mass1G', 'temp1C', 'mass2G', 'temp2C'],
  ),
  m(
    '3.2', 'Chimie', S6,
    '[Chimie·6e] Mélanges, corps purs et test à l’eau de chaux — Joseph Black (Édimbourg, 1754)',
    "En chauffant de la « magnésie blanche », Black isole un gaz qui éteint la flamme et trouble l'eau de chaux : le dioxyde de carbone, premier « air » identifié par un test reproductible.",
    "Évaporer une eau minérale laisse un résidu sec : sa concentration = masse du résidu (mg) / volume évaporé (L). « Homogène » ne veut pas dire « pur ».",
    'dissolved-solids', 'Résidu sec (mg/L)', ['residueMassMg', 'sampleVolumeL'],
  ),
  m(
    '3.3', 'Chimie', S5,
    '[Chimie·5e] La distillation — Marie la Juive (Alexandrie) ; Jabir ibn Hayyan ; al-Razi',
    "Séparer les constituants d'un liquide en jouant sur leurs températures d'ébullition est un savoir ancien : l'alambic et le bain-marie remontent à l'Alexandrie hellénistique et au monde arabo-persan.",
    "Rendement d'une distillation = volume de distillat recueilli / volume initial, exprimé en pourcentage. Seule l'eau se vaporise puis se condense à part.",
    'distillation-yield', 'Rendement de distillation (%)', ['distillateVolumeMl', 'initialVolumeMl'],
  ),
  m(
    '3.4', 'Chimie', S5,
    '[Chimie·5e] La dissolution et la conservation de la masse — Lavoisier (Traité, 1789)',
    "Quand on dissout du sucre dans l'eau, il disparaît à la vue. Lavoisier énonce en 1789 que « rien ne se perd » : la balance ne bouge pas.",
    "Lors d'une dissolution, la masse de la solution = masse du soluté + masse du solvant : le soluté invisible n'est pas perdu.",
    'solution-mass', 'Masse de la solution (g)', ['soluteMassG', 'solventMassG'],
  ),
  m(
    '3.5', 'Chimie', S5,
    '[Chimie·5e] La chromatographie — Mikhaïl Tsvet (Varsovie, 1900-1906)',
    "Cherchant si le vert des feuilles est une seule substance, Tsvet fait migrer un extrait végétal dans un tube de poudre blanche : les pigments se séparent en bandes de couleurs.",
    "Le rapport frontal Rf = distance parcourue par le constituant / distance parcourue par le solvant, entre 0 et 1. Deux Rf différents révèlent un mélange.",
    'retention-factor', 'Rapport frontal Rf', ['soluteMigrationMm', 'solventFrontMm'],
  ),
  m(
    '3.6', 'Chimie', S5,
    "[Chimie·5e] La conservation de la masse : la pesée — Lavoisier, calcination de l'étain (v. 1774)",
    "Contre la théorie du phlogistique, Lavoisier chauffe de l'étain en vase scellé : la masse totale ne change pas, et le métal calciné s'est alourdi de la masse d'air entré à l'ouverture.",
    "En système fermé, la masse ne change pas : l'écart (masse des produits − masse des réactifs) doit être proche de zéro, quelles que soient les transformations internes.",
    'mass-balance', "Écart de masse (g)", ['reactantsMassG', 'productsMassG'],
  ),
  m(
    '3.7', 'Chimie', S4,
    "[Chimie·4e] La composition de l'air — Priestley (1774) ; Lavoisier (expérience des 12 jours)",
    "Priestley, Scheele et Rutherford isolent vers 1774 les « airs » qui composent l'atmosphère. Lavoisier chauffe du mercure douze jours : le volume d'air diminue d'environ un cinquième.",
    "Quand une combustion ou une oxydation consomme le dioxygène d'un volume d'air clos, l'eau monte : fraction de dioxygène = montée d'eau / volume d'air initial (≈ 0,21).",
    'oxygen-fraction', 'Fraction de dioxygène', ['waterRiseMl', 'initialAirMl'],
  ),
  m(
    '3.8', 'Chimie', S4,
    "[Chimie·4e] Le modèle de l'atome et de la molécule — Démocrite ; Dalton (1808) ; Perrin (1908)",
    "L'atomisme, hypothèse philosophique chez Démocrite, redevient scientifique avec Dalton (loi des proportions multiples, 1808), puis est confirmé par Perrin en mesurant le mouvement brownien.",
    "En mélangeant deux liquides comme l'eau et l'alcool, le volume total est inférieur à la somme : contraction = (V₁ + V₂) − V(mélange), signe que la matière est faite de grains séparés par du vide.",
    'volume-contraction', 'Contraction de volume (mL)', ['volumeAMl', 'volumeBMl', 'mixedVolumeMl'],
  ),
  m(
    '3.9', 'Chimie', S4,
    "[Chimie·4e] Les combustions et le rôle du dioxygène — Lavoisier contre le phlogistique",
    "Lavoisier renverse l'explication de la combustion : brûler, c'est se combiner avec le dioxygène de l'air. Une bougie sous cloche s'éteint quand ce dioxygène est épuisé.",
    "La durée de combustion d'une bougie sous cloche est proportionnelle au volume d'air disponible (triangle du feu : combustible + comburant + chaleur).",
    'combustion-duration', 'Durée de combustion estimée (s)', ['referenceVolumeMl', 'referenceTimeS', 'targetVolumeMl'],
  ),
  m(
    '3.10', 'Chimie', S4,
    "[Chimie·4e] L'équation de réaction et la conservation des atomes — Lavoisier + Dalton ; Berzelius",
    "Avec le modèle atomique de Dalton, la conservation de la masse prend un sens plus profond : une transformation ne fait que redistribuer des atomes indestructibles.",
    "Les atomes se réarrangent sans disparaître : la masse totale des produits est égale à la somme des masses des réactifs.",
    'conserved-product-mass', 'Masse totale des produits (g)', ['reactant1MassG', 'reactant2MassG'],
  ),
  m(
    '3.11', 'Chimie', S3,
    "[Chimie·3e] L'électrolyse et la synthèse de l'eau — Nicholson et Carlisle (Londres, 1800)",
    "Quelques semaines après l'annonce de la pile de Volta, Nicholson et Carlisle plongent deux fils dans l'eau : un gaz se dégage à chaque fil, dans le rapport de volumes 2 pour 1.",
    "L'électrolyse de l'eau produit du dihydrogène et du dioxygène dans un rapport de volumes proche de 2 : V(H₂) / V(O₂).",
    'electrolysis-gas-ratio', 'Rapport V(H₂) / V(O₂)', ['hydrogenVolumeMl', 'oxygenVolumeMl'],
  ),
  m(
    '3.12', 'Chimie', S3,
    "[Chimie·3e] Métaux, rouille et oxydoréduction — Lavoisier ; Goldschmidt (1893) ; Sorel (1837)",
    "Calciner un métal, c'est le combiner avec l'oxygène : lentement (la rouille) ou vivement (la laine de fer qui brûle en étincelles). L'opération inverse arrache l'oxygène à l'oxyde.",
    "En s'oxydant, un métal fixe le dioxygène de l'air : gain de masse = masse finale − masse initiale (positif).",
    'oxidation-mass-gain', 'Gain de masse (g)', ['initialMassG', 'finalMassG'],
  ),
  m(
    '3.13', 'Chimie', S3,
    '[Chimie·3e] Acides, bases et pH — Robert Boyle (1664) ; Sørensen (1909)',
    "Boyle remarque que le sirop de violette et la teinture de tournesol changent de couleur selon le liquide : les premiers indicateurs colorés. En 1909, Sørensen introduit l'échelle chiffrée de pH.",
    "Diluer un acide fort d'un facteur k divise la concentration en ions H⁺ par k, donc augmente le pH de log₁₀(k), sans jamais dépasser la neutralité.",
    'diluted-acid-ph', 'pH après dilution', ['initialPh', 'dilutionFactor'],
  ),
  m(
    '3.14', 'Chimie', S3,
    '[Chimie·3e] Les ions et la conductivité des solutions — Faraday (1834) ; Arrhenius (1884)',
    "Faraday forge le vocabulaire d'« ion » et d'« électrode ». Arrhenius soutient en 1884 que certains composés sont déjà dissociés en ions dans la solution, ce qui la rend conductrice.",
    "Plus une solution contient d'ions, mieux elle conduit : le rapport intensité(solution) / intensité(eau de référence) mesure cet apport.",
    'conductivity-ratio', 'Rapport de conductivité', ['solutionCurrentMa', 'referenceCurrentMa'],
  ),

  // ------------------------- M4 · SVT -------------------------
  m(
    '4.1', 'SVT', S6,
    '[SVT·6e] La cellule, unité du vivant — Hooke (1665) ; Leeuwenhoek ; Schleiden et Schwann',
    "Hooke observe dans le liège des logettes qu'il nomme « cellules » ; Leeuwenhoek découvre les « animalcules ». En 1838-1839, Schleiden et Schwann énoncent que tout être vivant est fait de cellules.",
    "Au microscope, la taille d'une cellule = diamètre du champ observé / nombre de cellules alignées en travers du champ.",
    'cell-size', "Taille d'une cellule (µm)", ['fieldOfViewUm', 'cellsAcrossField'],
  ),
  m(
    '4.2', 'SVT', S6,
    '[SVT·6e] Classer le vivant : les groupes emboîtés — Linné (1735) ; Hennig (1950)',
    "Linné attribue à chaque espèce un nom en deux mots et une hiérarchie de rangs. Hennig propose en 1950 de classer par les caractères nouveaux partagés, en groupes emboîtés comme des poupées russes.",
    "On classe par ce que les êtres ont en commun : la part d'attributs partagés = attributs communs / attributs observés.",
    'shared-trait-ratio', "Part d'attributs partagés", ['sharedTraits', 'observedTraits'],
  ),
  m(
    '4.3', 'SVT', S6,
    "[SVT·6e] Les fossiles et l'histoire de la Terre — Nicolas Sténon (Florence, 1667-1669)",
    "Sténon compare les « langues de pierre » de Malte aux dents d'un requin disséqué : ce sont des dents fossiles. Il énonce le principe de superposition des strates.",
    "En connaissant la vitesse de sédimentation, l'âge d'une strate se déduit de sa profondeur : âge = profondeur / vitesse.",
    'stratum-age', 'Âge relatif de la strate (ans)', ['depthCm', 'sedimentationRateCmPerCentury'],
  ),
  m(
    '4.4', 'SVT', S6,
    "[SVT·6e] Des espèces disparues : la réalité de l'extinction — Cuvier (Muséum de Paris, 1796)",
    "En comparant les os d'éléphants vivants et des grands os fossiles de Sibérie, Cuvier démontre que le mammouth est une espèce distincte, éteinte : le monde vivant a une histoire.",
    "On compare une structure homologue entre forme fossile et forme actuelle : rapport = mesure fossile / mesure actuelle. Un écart net et constant signe une espèce distincte.",
    'morphological-ratio', 'Rapport morphologique', ['fossilMeasureMm', 'livingMeasureMm'],
  ),
  m(
    '4.5', 'SVT', S6,
    "[SVT·6e] D'où vient la matière des plantes ? — Van Helmont, expérience du saule (v. 1640)",
    "Van Helmont plante une bouture de 2,3 kg dans 90 kg de terre sèche, n'arrose qu'à l'eau de pluie : cinq ans plus tard l'arbre pèse ~77 kg et la terre n'a presque rien perdu.",
    "La matière produite par la plante = masse finale − masse initiale du plant, à comparer à la perte de masse (quasi nulle) de la terre.",
    'plant-mass-gain', 'Matière produite par la plante (g)', ['initialPlantMassG', 'finalPlantMassG'],
  ),
  m(
    '4.6', 'SVT', S6,
    "[SVT·6e] Humus, décomposeurs et vers de terre — Darwin, Down House (1837-1881)",
    "Pendant quarante ans, Darwin mesure l'enfoncement d'une « pierre à vers » et estime que les vers font passer plusieurs tonnes de terre par hectare et par an, enfouissant la litière.",
    "Les vers de terre remontent le sol : vitesse d'enfouissement d'une dalle témoin = enfoncement mesuré / durée, en mm par jour.",
    'burial-rate', "Vitesse d'enfouissement (mm/jour)", ['sinkingMm', 'durationDays'],
  ),
  m(
    '4.7', 'SVT', S6,
    '[SVT·6e] Micro-organismes et transformation des aliments — Appert (v. 1795-1810) ; Pasteur (1857)',
    "Appert conserve les aliments par chauffage en bocal scellé, sans savoir pourquoi. Pasteur montre que fermentations et altérations sont l'œuvre de micro-organismes vivants.",
    "Les micro-organismes (levure) font lever la pâte : coefficient de levée = hauteur finale / hauteur initiale (1 = pas de levée, sans levure).",
    'dough-rise-ratio', 'Coefficient de levée de la pâte', ['finalHeightMm', 'initialHeightMm'],
  ),
  m(
    '4.8', 'SVT', S5,
    '[SVT·5e] Les séismes : ondes, foyer et épicentre — Michell (1760) ; Milne (1880) ; Richter (1935)',
    "Après le séisme de Lisbonne (1755), Michell propose qu'un tremblement de terre est une onde élastique partant d'un foyer. Milne construit le sismographe moderne, Richter l'échelle de magnitude.",
    "Règle d'Omori : la distance à l'épicentre (km) vaut environ 8 fois l'écart de temps d'arrivée entre l'onde lente (S) et l'onde rapide (P), en secondes.",
    'epicentral-distance', "Distance à l'épicentre (km)", ['sMinusPSeconds'],
  ),
  m(
    '4.9', 'SVT', S5,
    "[SVT·5e] Les volcans : le témoignage du Vésuve — Pline le Jeune (79 apr. J.-C.)",
    "Depuis Misène, Pline le Jeune décrit dans deux lettres à Tacite le nuage « en pin parasol », les retombées de cendres et la mort de son oncle : le premier compte rendu précis d'une éruption.",
    "Une lave fluide (éruption effusive) s'écoule : sa vitesse = distance parcourue par le front de coulée / durée.",
    'lava-flow-speed', 'Vitesse de la coulée (m/s)', ['flowDistanceM', 'durationS'],
  ),
  m(
    '4.10', 'SVT', S5,
    "[SVT·5e] La respiration : le dioxygène et l'organisme — Lavoisier et Séguin (Paris, 1790)",
    "Lavoisier mesure le dioxygène consommé et le dioxyde de carbone rejeté par Séguin au repos, en digestion et à l'effort : la respiration est une combustion lente qui s'intensifie avec l'activité.",
    "Débit ventilatoire = volume d'un souffle × nombre de respirations par minute. Il augmente nettement à l'effort.",
    'ventilation-rate', 'Débit ventilatoire (mL/min)', ['breathVolumeMl', 'breathsPerMinute'],
  ),
  m(
    '4.11', 'SVT', S5,
    '[SVT·5e] La digestion : une transformation chimique — Spallanzani (v. 1780) ; Beaumont (1822-1833)',
    "Spallanzani avale des tubes contenant de la viande et montre qu'elle est dissoute sans être écrasée. Beaumont observe la digestion à travers la fistule d'estomac d'Alexis Saint-Martin.",
    "La digestion est une transformation chimique : vitesse = fraction d'amidon transformée / durée (min). Elle est nulle sans salive ou à froid.",
    'digestion-rate', 'Vitesse de digestion (fraction/min)', ['transformedFraction', 'durationMin'],
  ),
  m(
    '4.12', 'SVT', S5,
    '[SVT·5e] Micro-organismes, hygiène et transmission — Semmelweis (1847) ; John Snow (1854)',
    "Semmelweis impose le lavage des mains chlorées et fait chuter la fièvre puerpérale. Snow cartographie une flambée de choléra à Soho et la relie à la pompe de Broad Street.",
    "Enquête de terrain : taux d'attaque d'une source suspecte = nombre de malades exposés / nombre total d'exposés à cette source.",
    'attack-rate', "Taux d'attaque", ['cases', 'exposed'],
  ),
  m(
    '4.13', 'SVT', S4,
    '[SVT·4e] La photosynthèse : convertir la lumière en matière — Ingenhousz (1779) ; de Saussure (1804) ; Sachs (1862)',
    "Ingenhousz montre que les plantes ne purifient l'air qu'à la lumière et par leurs parties vertes ; Sachs révèle l'amidon formé dans les feuilles éclairées.",
    "À la lumière, l'élodée dégage du dioxygène : le débit de bulles (bulles / minute) mesure l'intensité de la photosynthèse.",
    'photosynthesis-bubble-rate', 'Débit de bulles (bulles/min)', ['bubbleCount', 'durationMinutes'],
  ),
  m(
    '4.14', 'SVT', S4,
    "[SVT·4e] L'ADN et l'hérédité — Mendel, jardin du monastère de Brno (1856-1863)",
    "Mendel croise près de 30 000 plants de pois et découvre des régularités numériques : un caractère peut sauter une génération, et les proportions de la 2ᵉ génération approchent 3 pour 1.",
    "À la deuxième génération, le rapport (individus à caractère dominant) / (individus à caractère récessif) se rapproche de 3.",
    'phenotype-ratio', 'Rapport dominant / récessif', ['dominantCount', 'recessiveCount'],
  ),
  m(
    '4.15', 'SVT', S4,
    '[SVT·4e] La circulation du sang et le rôle du cœur — William Harvey (Londres, 1628)',
    "Harvey calcule qu'en une heure le cœur chasse bien plus de sang que n'en contient le corps : il est impossible que le sang soit sans cesse fabriqué et détruit, il circule en boucle.",
    "Débit cardiaque = volume chassé par battement × fréquence cardiaque. En une heure, il dépasse la masse du corps.",
    'cardiac-output', 'Débit cardiaque (mL/min)', ['strokeVolumeMl', 'heartRateBpm'],
  ),
  m(
    '4.16', 'SVT', S4,
    "[SVT·4e] Le cycle du carbone et l'effet de serre — Fourier (1824) ; Tyndall (1859) ; Keeling (1958)",
    "Fourier propose que l'atmosphère retient une partie de la chaleur ; Tyndall mesure l'absorption du rayonnement par le CO₂ ; Keeling suit depuis 1958 la hausse continue du CO₂ atmosphérique.",
    "Deux bocaux au soleil : celui enrichi en dioxyde de carbone monte plus haut en température. Écart = température du bocal CO₂ − température du bocal air.",
    'greenhouse-warming', 'Écart de température (°C)', ['co2JarTempC', 'airJarTempC'],
  ),
  m(
    '4.17', 'SVT', S4,
    '[SVT·4e] La tectonique des plaques — Wegener (1912) ; océanographie des années 1960',
    "Wegener avance que les continents formaient un seul bloc, la Pangée, aujourd'hui fragmenté. L'exploration des dorsales océaniques dans les années 1960 confirme que le plancher se crée et s'écarte.",
    "Les plaques bougent de quelques centimètres par an : déplacement = vitesse × durée.",
    'plate-displacement', 'Déplacement de la plaque (cm)', ['rateCmPerYear', 'years'],
  ),
  m(
    '4.18', 'SVT', S4,
    '[SVT·4e] Le système immunitaire et la vaccination — Jenner (1796) ; Pasteur, Pouilly-le-Fort (1881)',
    "Jenner inocule à James Phipps de la vaccine, puis la variole : l'enfant ne tombe pas malade. En 1881, Pasteur organise à Pouilly-le-Fort un essai public à deux lots contre le charbon.",
    "Essai contrôlé à deux lots : efficacité (%) = (1 − taux d'attaque du lot vacciné / taux d'attaque du lot témoin) × 100.",
    'vaccine-efficacy', 'Efficacité vaccinale (%)', ['controlAttackRate', 'vaccinatedAttackRate'],
  ),
  m(
    '4.19', 'SVT', S3,
    '[SVT·3e] La valeur énergétique des aliments — Lavoisier & Laplace (1782-1783) ; Atwater',
    "Lavoisier et Laplace mesurent la chaleur d'un cochon d'Inde avec un calorimètre à glace ; Atwater construit une chambre calorimétrique humaine et publie les « facteurs » encore utilisés sur les emballages.",
    "Calorimétrie de terrain : l'énergie libérée par un aliment qui brûle sous un récipient d'eau = masse d'eau × 4,2 × élévation de température (en joules).",
    'food-energy', 'Énergie libérée (J)', ['waterMassG', 'temperatureRiseC'],
  ),
  m(
    '4.20', 'SVT', S3,
    '[SVT·3e] Les sols : fertilité et érosion — Boussingault (1834) ; Liebig (1840)',
    "Boussingault pèse tout ce qui entre et sort de ses parcelles ; Liebig montre que les plantes prélèvent des éléments minéraux dans le sol. Le Dust Bowl des années 1930 illustre le coût d'un sol nu.",
    "Test d'infiltration : vitesse à laquelle un sol absorbe l'eau = volume versé / temps d'infiltration (mL/s). Un sol fertile est perméable.",
    'infiltration-rate', "Vitesse d'infiltration (mL/s)", ['waterVolumeMl', 'infiltrationTimeS'],
  ),
  m(
    '4.21', 'SVT', S5,
    '[SVT·5e] La reproduction sexuée et la fécondation — Camerarius, De sexu plantarum (1694)',
    "En retirant les étamines d'une fleur ou en isolant un pied femelle, Camerarius obtient des fruits sans graines viables : première démonstration expérimentale de la sexualité végétale.",
    "Taux de nouaison = nombre de fleurs ayant donné un fruit / nombre de fleurs suivies. Il s'effondre pour les fleurs isolées de tout pollen.",
    'fruit-set-rate', 'Taux de nouaison', ['fruitCount', 'flowerCount'],
  ),
];
